spring:
  application:
    name: health-data-java
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
        current_session_context_class: thread
        format_sql: true
    open-in-view: false

server:
  servlet:
    context-path: /health-data

management:
  endpoints:
    web:
      exposure:
        include: '*'
